## Numpy

In [3]:
import numpy as np

arr = np.array([2,5,7,4,9,8])
print(arr)
arr.shape

[2 5 7 4 9 8]


(6,)

In [4]:
list = [1,2,3,4]
list_b = [5,6,7,8]
arr = np.array([list,list_b])
print(arr)
arr.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr.reshape(3,3)
arr[1:4]

array([2, 3, 4])

In [6]:
arr = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
arr.reshape(1,9)
arr[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [7]:
np.linspace(2,10,5)
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [8]:
arr = np.arange(0,10)
arr[3:]=100
print(arr)

[  0   1   2 100 100 100 100 100 100 100]


In [9]:
arr = np.arange(0,10)
arr1 = arr.copy()
arr[3:]=100
print(arr)
print(arr1)

[  0   1   2 100 100 100 100 100 100 100]
[0 1 2 3 4 5 6 7 8 9]


In [10]:
np.random.randint(0,10,6).reshape(2,3)

array([[6, 2, 1],
       [7, 2, 4]])

## Practice

In [11]:
arr = np.array([5,25,52,65,86,84,25,75])
print(arr)
print(arr.reshape(2,4))
print(arr.dtype)
arr.shape

[ 5 25 52 65 86 84 25 75]
[[ 5 25 52 65]
 [86 84 25 75]]
int64


(8,)

In [12]:
arr = np.array([1,2,3,4,5,6])
arr.reshape(2,3)
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[0])
print(arr[3])
print(arr[-1])

1
4
9


In [14]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6]])
print(arr)
arr[2:,2:4]

[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]]


array([[7, 6]])

In [15]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
np.arange(0,10)
np.arange(0,20,5)
np.linspace(1,5,5)

[[1 2 3 4]
 [5 6 7 8]]


array([1., 2., 3., 4., 5.])

In [16]:
arr = np.arange(0,10)
arr[3:]=100
print(arr)

[  0   1   2 100 100 100 100 100 100 100]


In [17]:
arr = np.arange(0,10)
arr1 = arr.copy()
arr1[3:]=100
print(arr)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[  0   1   2 100 100 100 100 100 100 100]


In [18]:
arr = np.array([1,2,3,4,5])
print(arr*2)
print(arr+2)
print(arr%2)
print(arr/2)

[ 2  4  6  8 10]
[3 4 5 6 7]
[1 0 1 0 1]
[0.5 1.  1.5 2.  2.5]


In [19]:
arr = np.array([10,20,41,37,23,30,40,50])
print(arr>25)
print(arr<40)
print(arr%2==0)

[False False  True  True False  True  True  True]
[ True  True False  True  True  True False False]
[ True  True False False False  True  True  True]


In [20]:
arr = np.ones((2,3),dtype=int)
print(arr)


[[1 1 1]
 [1 1 1]]


In [29]:
ls1 = [1,2,3,4,5]
ls2 = [6,7,8,9,10]
ls3 = [11,12,13,14,15]
arr2d = np.array([ls1,ls2,ls3])
print(arr2d)
arr2d.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


(3, 5)