## Numpy

In [2]:
import numpy as np

### Practice Questions

Q1. Create a NumPy array of numbers from 1 to 20. Then reshape it into a 4×5 matrix and print:
1. The matrix
2. The shape
3. The data type

In [38]:
arr = np.arange(1,21).reshape(4,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Q2. From the 4×5 matrix you created earlier, do the following:

1. Print the first row
2. Print the last column
3. Print the element at 3rd row, 4th column
4. Print all elements greater than 10

In [39]:
arr[0]

array([1, 2, 3, 4, 5])

In [40]:
arr[:,-1]

array([ 5, 10, 15, 20])

In [41]:
arr[2,3]

np.int64(14)

In [42]:
arr[arr>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

Q3. Using the same 4×5 matrix, perform the following operations:

1. Add 10 to every element
2. Multiply each element by 2
3. Square each element
4. Create a new array where each element is divided by 2 (use float division)

In [45]:
arr+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [46]:
arr*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [47]:
arr**2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400]])

In [48]:
arr/2

array([[ 0.5,  1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5,  5. ],
       [ 5.5,  6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5, 10. ]])