## Numpy

In [2]:
import numpy as np

### Practice Questions

#### Q1. Create a NumPy array of numbers from 1 to 20. Then reshape it into a 4×5 matrix and print:
1. The matrix
2. The shape
3. The data type

In [3]:
arr = np.arange(1,21).reshape(4,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


#### Q2. From the 4×5 matrix you created earlier, do the following:

1. Print the first row
2. Print the last column
3. Print the element at 3rd row, 4th column
4. Print all elements greater than 10

In [4]:
arr[0]

array([1, 2, 3, 4, 5])

In [5]:
arr[:,-1]

array([ 5, 10, 15, 20])

In [6]:
arr[2,3]

np.int64(14)

In [7]:
arr[arr>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

#### Q3. Using the same 4×5 matrix, perform the following operations:

1. Add 10 to every element
2. Multiply each element by 2
3. Square each element
4. Create a new array where each element is divided by 2 (use float division)

In [8]:
arr+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [9]:
arr*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [10]:
arr**2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400]])

In [11]:
arr/2

array([[ 0.5,  1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5,  5. ],
       [ 5.5,  6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5, 10. ]])

#### Q4. Using the same 4×5 NumPy array, perform these operations:

1. Find the sum of all elements
2. Find the mean (average) of all elements
3. Find the maximum and minimum value
4. Find the sum of each column
5. Find the mean of each row

In [12]:
arr.sum()

np.int64(210)

In [13]:
arr.mean()

np.float64(10.5)

In [14]:
arr.max()

np.int64(20)

In [15]:
arr.min()

np.int64(1)

In [16]:
arr.sum(axis=0)

array([34, 38, 42, 46, 50])

In [17]:
arr.mean(axis=1)

array([ 3.,  8., 13., 18.])

#### Q5. Using the same 4×5 NumPy array, do the following:

1. Extract a submatrix containing rows 2 to 4 and columns 2 to 5
2. Reverse the order of rows
3. Reverse the order of columns
4. Extract all elements at even indices (both row and column)

In [18]:
arr[1:3,1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [20]:
arr[::-1]

array([[16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [21]:
arr[:,::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16]])

In [22]:
arr[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

#### Q6. Using NumPy, perform the following:

1. Create two arrays:\
    A = numbers from 1 to 9 reshaped into 3×3\
    B = numbers from 10 to 18 reshaped into 3×3
2. Perform:\
    Element-wise addition of A and B\
    Element-wise multiplication of A and B\
    Matrix multiplication of A and B

In [24]:
A = np.arange(1,10).reshape(3,3)
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
B = np.arange(10,19).reshape(3,3)
print(B)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [27]:
A + B

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [28]:
A * B

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [29]:
np.dot(A,B) # or A @ B

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])